git:
  branchLogCmd: git log --all --decorate --oneline --graph --stat --color=always --abbrev-commit

notARepository: skip
gui:
  nerdFontsVersion: "3"

keybinding:
  stash:
    popStash: p
    renameStash: r
