git:
  branchLogCmd: git log --all --decorate --oneline --graph --stat --color=always --abbrev-commit
notARepository: skip
gui:
  nerdFontsVersion: "3"
  border: rounded
  theme: 
    # Cyberdream
    # https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/lazygit/cyberdream.yml
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
keybinding:
  stash:
    popStash: p
    renameStash: r
