- name: Check if .dotfiles repo already exists
  stat:
    path: "{{ ansible_env.HOME }}/.dotfiles/.git"
  register: dotfiles_repo

- name: Clone .dotfiles from GitHub to $HOME
  git:
    repo: git@github.com:csessh/.dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    version: main
    update: yes
  when: not dotfiles_repo.stat.exists
  ignore_errors: True
