- name: Ensure all dnf packages are updated (Fedora)
  become: yes
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Add Fyra Labs Terra repository (Required for Pet)
  become: yes
  yum_repository:
    name: fyralabs-terra
    description: Fyra Labs Terra Repository
    baseurl: https://repos.fyralabs.com/terra$releasever
    enabled: yes
    gpgcheck: no

- name: Install dnf packages (Fedora)
  become: yes
  ansible.builtin.dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ packages }}"
