- name: Add Fyra Labs Terra repository (Required for Pet)
  become: yes
  yum_repository:
    name: fyralabs-terra
    description: Fyra Labs Terra Repository
    baseurl: https://repos.fyralabs.com/terra$releasever
    enabled: yes
    gpgcheck: no

- name: Add COPR repository (Required for lazygit)
  become: yes
  command: sudo dnf copr enable atim/lazygit -y
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo

- name: Add 1Password repository
  become: yes
  copy:
    dest: /etc/yum.repos.d/1password.repo
    content: |
      [1password]
      name=1Password Stable Channel
      baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://downloads.1password.com/linux/keys/1password.asc
    mode: '0644'

- name: Add Docker repository
  become: yes
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Ensure all dnf packages are updated (Fedora)
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install packages with dnf (Fedora)
  become: yes
  dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ packages }}"
  ignore_errors: yes 
