- name: Install dnf config manager
  become: yes
  dnf:
    name: dnf-plugins-core
    update_cache: yes
    state: latest

- name: Add Docker repository
  become: yes
  command: dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Add COPR repository (Required for lazygit)
  become: yes
  command: sudo dnf copr enable atim/lazygit -y
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo

- name: Add 1Password repository
  become: yes
  copy:
    dest: /etc/yum.repos.d/1password.repo
    content: |
      [1password]
      name=1Password Stable Channel
      baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://downloads.1password.com/linux/keys/1password.asc
    mode: '0644'

- name: Ensure all dnf packages are updated (Fedora)
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install packages with dnf (Fedora)
  become: yes
  dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ packages }}"
  ignore_errors: yes
