- name: Ensure font directory exists
  file:
    path: "~/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Download Fira Mono font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraMono.zip"
    dest: "~/.local/share/fonts/FiraMono.zip"

- name: Unzip Fira Mono font
  unarchive:
    src: "~/.local/share/fonts/FiraMono.zip"
    dest: "~/.local/share/fonts"
    remote_src: yes
    creates: "~/.local/share/fonts/FiraMono-Regular.ttf"

- name: Remove the ZIP file
  file:
    path: "~/.local/share/fonts/FiraMono.zip"
    state: absent

- name: Refresh font cache
  command: fc-cache -fv
