- name: Ensure font directory exists
  file:
    path: "~/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Download Commit Mono font
  get_url:
    url: "https://github.com/eigilnikolajsen/commit-mono/releases/download/v1.143/CommitMono-1.143.zip"
    dest: "~/.local/share/fonts/CommitMono.zip"

- name: Unzip Commit Mono font
  unarchive:
    src: "~/.local/share/fonts/CommitMono.zip"
    dest: "~/.local/share/fonts"
    remote_src: yes
    creates: "~/.local/share/fonts/CommitMono-Regular.ttf"

- name: Remove the ZIP file
  file:
    path: "~/.local/share/fonts/CommitMono.zip"
    state: absent

- name: Refresh font cache
  command: fc-cache -fv
