- name: Remove stock htoprc
  file:
    path: ~/.config/htop/htoprc
    state: absent

- name: Simulate stow
  shell:
    cmd: stow htop --simulate -v
    chdir: ~/.dotfiles/
  register: sim_result
  changed_when: False

- name: Stow dotfiles
  shell:
    cmd: stow htop
    chdir: ~/.dotfiles
  when: '"LINK: " in sim_result.stderr'

