- name: Simulate stow
  ansible.builtin.shell:
    cmd: stow htop --simulate -v
    chdir: ~/.dotfiles/
  register: sim_result
  changed_when: False

- name: Stow dotfiles
  ansible.builtin.shell:
    cmd: stow htop
    chdir: ~/.dotfiles
  when: '"LINK: " in sim_result.stderr'

