- name: Clone TPM repo (plugin manager)
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    update: yes
    force: yes

- name: Simulate stow
  shell:
    cmd: stow tmux --simulate -v
    chdir: ~/.dotfiles/
  register: sim_result
  changed_when: False

- name: Stow dotfiles
  shell:
    cmd: stow tmux
    chdir: ~/.dotfiles
  when: '"LINK: " in sim_result.stderr'

