- name: The "I-specialise-in-automation" dotfiles playbook for remote servers
  roles:
    # Standard tools/packages
    - utils
    - git
    - docker

    # Tools which require specific configuration
    - bat
    - htop
    - neovim
    - shell
    - pet
