- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Get current user using whoami
  command: whoami
  register: current_user
  changed_when: False

- name: Add user to docker group (optional)
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    append: yes
  when: current_user.stdout != 'root'

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- name: Show installed Docker version
  debug:
    msg: "Docker version installed: {{ docker_version.stdout }}"
