- name: The "I-specialise-in-automation" dotfiles playbook
  hosts: linode
  roles:
    # Standard tools/packages
    - utils
    - git
    - docker

    # Tools which require specific configuration
    - bat
    - htop
    - kitty
    - pet

    # Other essentials
    - tmux
    - neovim
    - 1password
    - shell
