- name: The "I-specialise-in-automation" dotfiles playbook
  vars:
    playbook_id: localhost_playbook
  hosts: local
  roles:
    # Standard tools/packages
    - ssh
    - docker
    - git
    - utils

    # Tools which require specific configuration
    - 1password
    - aider
    - bat
    - fastfetch
    - htop
    - kitty
    - neovim
    - pet
    - shell
