- name: The "I-specialise-in-automation" dotfiles playbook for remote servers
  hosts: all
  vars:
    playbook_id: remote_playbook
  roles:
    # Standard tools/packages
    - ssh
    - utils
    - git

    # Tools which require specific configuration
    - docker
    - bat
    - fastfetch
    - htop
    - neovim
    - pet
    - shell
