[General]
Backend = "gist"
Cmd = []
Color = true
Column = 50
Editor = "nvim"
Format = "[$tags] [$description] > $command"
SelectCmd = "fzf --ansi --highlight-line --layout=reverse --border --height=90% --pointer=* --cycle --prompt=Snippets:"
SnippetDirs = []
SnippetFile = "~/.config/pet/snippet.toml"
SortBy = "recency"

[Gist]
file_name = "pet.toml"
access_token = "op://uqphul5mggpu5cpyaljyu76nvy/GitHub Gist PAT/token"
gist_id = "307fa561001fb7f5d235ca1ab4839191"
public = true
auto_sync = false
