[[Snippets]]
  Description = "Snipe/Terminate an existing process"
  Filename = "/home/csessh/.config/pet/snippet.toml"
  Output = ""
  Tag = ["fzf"]
  command = "ps aux | fzf --height=40% --layout=reverse --prompt=\"Which process are we killing? > \" | awk '{print $2}' | xargs -r sudo kill"
